replicaCount: 2

image:
  tag: "latest"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
  - name: VERSION
    value: "1.0.0"

